language: python
python:
  - "2.7"
  - "3.5"
env:
  matrix:
    - DJANGO_VERSION="django>=1.8,<1.9"
    - DJANGO_VERSION="django>=1.9,<1.10"
    - DJANGO_VERSION="django>=1.10,<1.11"
install:
  - pip install -e . -r requirements.txt $DJANGO_VERSION
  - pip install coveralls
script:
  - coverage run --source=report_builder manage.py test
  - flake8
after_success:
  coveralls
sudo: false
