# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0006_auto_20150904_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
